name: dotnet


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
      with:
        dotnet-version: 3.1.402
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o dotnetcorewebapp
